{
  imports = [
    ./chrome.nix
    ./chromium.nix
    ./design.nix
    ./developmentTools.nix
    ./editor.nix
    ./encryption.nix
    ./fileManager.nix
    ./firefox/firefox.nix
    ./git.nix
    ./homeManagement.nix
    ./homePackages.nix
    ./hypr/hyprland.nix
    ./hypr/hyprlock.nix
    ./impermanence.nix
    ./librewolf.nix
    ./lynx.nix
    ./passwordManagement.nix
    ./rofi.nix
    ./shell.nix
    ./virtualization.nix
    ./waybar.nix
  ];
}
