{
  imports = [
    ./browser
    ./design.nix
    ./developmentTools.nix
    ./editor.nix
    ./encryption.nix
    ./fileManager.nix
    ./homeManagement.nix
    ./homePackages.nix
    ./hyprland.nix
    ./impermanence.nix
    ./passwordManagement.nix
    ./rofi.nix
    ./shell.nix
    ./virtualization.nix
    ./waybar.nix
  ];
}
