{
  imports = [
    ./browser.nix
    ./compositor.nix
    ./design.nix
    ./editor.nix
    ./encryption.nix
    ./fileManager.nix
    ./homeEnvironment.nix
    ./homeManagement.nix
    ./homePackages.nix
    ./hyprland.nix
    ./passwordManagement.nix
    ./rofi.nix
    ./shell.nix
    ./status.nix
    ./virtualization.nix
  ];
}
