{
  imports = [
    ./audio.nix
    ./boot.nix
    ./deploy.nix
    ./design.nix
    ./displayManager.nix
    ./environment.nix
    ./FHS.nix
    ./gaming.nix
    ./GNOME.nix
    ./laptopSupport.nix
    ./localization.nix
	./microphone.nix
    ./network.nix
    ./nixSettings.nix
	./qemuGuest.nix
    ./RGB.nix
    ./secrets.nix
    ./security.nix
    ./syncthing.nix
    ./ssh.nix
    ./systemMaintenance.nix
    ./tools.nix
    ./torrenting.nix
    ./transcience.nix
    ./users.nix
    ./virtualization.nix
	./wsl.nix
    ./yubikey.nix
  ];
}
